using LlamaStudio.Core.Interfaces;
using System.Collections.Generic;

namespace LlamaStudio.Core.Services;

public class LocalizationService : ILocalizationService
{
    string _language = "ru";

    public string Language
    {
        get => _language;
        set => ChangeLanguage(value);
    }

    readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        // Main window
        ["main.dashboard"] = new() { ["en"] = "Dashboard", ["ru"] = "Главная" },
        ["main.models"] = new() { ["en"] = "Models", ["ru"] = "Модели" },
        ["main.server"] = new() { ["en"] = "Server", ["ru"] = "Сервер" },
        ["main.profiles"] = new() { ["en"] = "Profiles", ["ru"] = "Профили" },
        ["main.logs"] = new() { ["en"] = "Logs", ["ru"] = "Логи" },
        ["main.apitest"] = new() { ["en"] = "API Test", ["ru"] = "Тест API" },
        ["main.chat"] = new() { ["en"] = "Chat", ["ru"] = "Чат" },
        ["main.settings"] = new() { ["en"] = "Settings", ["ru"] = "Настройки" },
        ["main.support"] = new() { ["en"] = "Discussion & Support", ["ru"] = "Обсуждение и поддержка" },
        ["main.start_server"] = new() { ["en"] = "Start Server", ["ru"] = "Запустить сервер" },
        ["main.server_running"] = new() { ["en"] = "Running", ["ru"] = "✓ Запущен" },
        ["main.stop_server"] = new() { ["en"] = "Stop Server", ["ru"] = "Остановить сервер" },
        ["main.server_stopped"] = new() { ["en"] = "Stopped", ["ru"] = "Остановлен" },
        ["main.restart_server"] = new() { ["en"] = "Restart Server", ["ru"] = "Перезапустить" },
        ["main.subtitle"] = new() { ["en"] = " — llama.cpp Manager", ["ru"] = " — менеджер llama.cpp" },
        ["main.monitoring"] = new() { ["en"] = "Monitoring", ["ru"] = "Мониторинг" },
        ["main.llama_releases"] = new() { ["en"] = "llama.cpp Releases", ["ru"] = "Релизы llama.cpp" },

        // Llama releases page
        ["llama_releases.title"] = new() { ["en"] = "llama.cpp Releases", ["ru"] = "Релизы llama.cpp" },
        ["llama_releases.releases_section"] = new() { ["en"] = "Available Releases", ["ru"] = "Доступные релизы" },
        ["llama_releases.check_updates"] = new() { ["en"] = "Check for Updates", ["ru"] = "Проверить обновления" },
        ["llama_releases.checking"] = new() { ["en"] = "Checking...", ["ru"] = "Проверка..." },
        ["llama_releases.installed_versions"] = new() { ["en"] = "Installed Versions", ["ru"] = "Установленные версии" },
        ["llama_releases.refresh"] = new() { ["en"] = "Refresh", ["ru"] = "Обновить" },
        ["llama_releases.install"] = new() { ["en"] = "Install", ["ru"] = "Установить" },
        ["llama_releases.installing"] = new() { ["en"] = "Installing...", ["ru"] = "Установка..." },
        ["llama_releases.installed"] = new() { ["en"] = "✓ Installed", ["ru"] = "✓ Установлено" },
        ["llama_releases.use"] = new() { ["en"] = "Use", ["ru"] = "Использовать" },
        ["llama_releases.remove"] = new() { ["en"] = "Remove", ["ru"] = "Удалить" },
        ["llama_releases.active"] = new() { ["en"] = "Active", ["ru"] = "Активна" },
        ["llama_releases.latest"] = new() { ["en"] = "Latest", ["ru"] = "Последняя" },
        ["llama_releases.no_releases"] = new() { ["en"] = "No releases found", ["ru"] = "Релизы не найдены" },
        ["llama_releases.restart_server"] = new() { ["en"] = "Restarting server with version \"{0}\"...", ["ru"] = "Перезапуск сервера с версией «{0}»..." },
        ["llama_releases.cannot_delete_active"] = new() { ["en"] = "Cannot delete the active version", ["ru"] = "Нельзя удалить активную версию" },
        ["llama_releases.delete_failed_folder"] = new() { ["en"] = "Failed to delete {0}:\nFolder was not removed.\n\nCheck that files are not in use by another process.", ["ru"] = "Не удалось удалить {0}:\nПапка не была удалена.\n\nПроверьте, что файлы не используются другим процессом." },
        ["llama_releases.delete_failed_error"] = new() { ["en"] = "Failed to delete {0}:\n{1}\n\nCheck that files are not in use by another process.", ["ru"] = "Не удалось удалить {0}:\n{1}\n\nПроверьте, что файлы не используются другим процессом." },
        ["llama_releases.switch_version"] = new() { ["en"] = "Switch Version", ["ru"] = "Сменить версию" },

        // Dashboard
        ["dash.update_version"] = new() { ["en"] = "Update ({0})", ["ru"] = "Обновить ({0})" },
        ["dash.not_installed"] = new() { ["en"] = "Not installed", ["ru"] = "Не установлено" },
        ["dash.no_model_selected"] = new() { ["en"] = "No model selected", ["ru"] = "Модель не выбрана" },
        ["dash.saved"] = new() { ["en"] = "saved", ["ru"] = "сохранено" },
        ["dash.default_badge"] = new() { ["en"] = "(default)", ["ru"] = "(по умолчанию)" },

        // Dialogs
        ["dialog.create_profile_title"] = new() { ["en"] = "Create Profile", ["ru"] = "Создать профиль" },
        ["dialog.profile_name_prompt"] = new() { ["en"] = "Enter profile name:", ["ru"] = "Введите имя профиля:" },
        ["dialog.profile_exists"] = new() { ["en"] = "A profile with the name \"{0}\" already exists.", ["ru"] = "Профиль с именем «{0}» уже существует." },
        ["dialog.profile_created"] = new() { ["en"] = "Profile \"{0}\" created.", ["ru"] = "Профиль «{0}» создан." },
        ["dialog.profile_updated"] = new() { ["en"] = "Profile \"{0}\" updated.", ["ru"] = "Профиль «{0}» обновлён." },
        ["dialog.settings_saved"] = new() { ["en"] = "Settings saved to profile \"{0}\".", ["ru"] = "Настройки сохранены в профиль «{0}»." },
        ["dialog.confirm_delete_profile"] = new() { ["en"] = "Are you sure you want to delete profile \"{0}\"?", ["ru"] = "Вы уверены, что хотите удалить профиль «{0}»?" },
        ["dialog.delete_profile_title"] = new() { ["en"] = "Delete Profile", ["ru"] = "Удалить профиль" },
        ["dialog.select_profile_first"] = new() { ["en"] = "Select a profile first.", ["ru"] = "Сначала выберите профиль." },
        ["dialog.no_other_profiles"] = new() { ["en"] = "No other profiles to copy from.", ["ru"] = "Нет других профилей для копирования." },
        ["dialog.copy_settings_title"] = new() { ["en"] = "Copy Settings", ["ru"] = "Копировать параметры" },
        ["dialog.rename_title"] = new() { ["en"] = "Rename", ["ru"] = "Переименовать" },
        ["dialog.rename_prompt"] = new() { ["en"] = "Enter new profile name:", ["ru"] = "Введите новое имя профиля:" },
        ["dialog.model_not_found"] = new() { ["en"] = "Model file not found:\n{0}", ["ru"] = "Файл модели не найден:\n{0}" },

        // Server dialogs
        ["server.restart_profile"] = new() { ["en"] = "Restarting server with profile \"{0}\"...", ["ru"] = "Перезапуск сервера с профилем «{0}»..." },
        ["server.already_running"] = new() { ["en"] = "Server is already running!", ["ru"] = "Сервер уже запущен!" },
        ["server.start_failed"] = new() { ["en"] = "Server failed to start.\n\n{0}", ["ru"] = "Не удалось запустить сервер.\n\n{0}" },
        ["server.start_error"] = new() { ["en"] = "Failed to start server:\n{0}", ["ru"] = "Ошибка запуска сервера:\n{0}" },
        ["server.stop_error"] = new() { ["en"] = "Failed to stop server:\n{0}", ["ru"] = "Ошибка остановки сервера:\n{0}" },
        ["server.restart_failed"] = new() { ["en"] = "Server failed to restart.\n\n{0}", ["ru"] = "Не удалось перезапустить сервер.\n\n{0}" },
        ["server.restart_error"] = new() { ["en"] = "Failed to restart server:\n{0}", ["ru"] = "Ошибка перезапуска сервера:\n{0}" },
        ["server.unknown_error"] = new() { ["en"] = "Unknown error", ["ru"] = "Неизвестная ошибка" },
        ["server.no_profile_selected"] = new() { ["en"] = "No profile selected.", ["ru"] = "Профиль не выбран." },
        ["server.no_model_selected"] = new() { ["en"] = "No model selected.", ["ru"] = "Модель не выбрана." },
        ["server.exe_not_found"] = new() { ["en"] = "llama-server.exe not found: {0}", ["ru"] = "llama-server.exe не найден: {0}" },
        ["server.exe_not_found_short"] = new() { ["en"] = "llama-server.exe not found", ["ru"] = "llama-server.exe не найден" },
        ["server.unknown_version"] = new() { ["en"] = "Unknown version", ["ru"] = "Неизвестная версия" },
        ["server.version_error"] = new() { ["en"] = "Error checking version: {0}", ["ru"] = "Ошибка проверки версии: {0}" },
        ["server.installed_unknown"] = new() { ["en"] = "Installed (version unknown)", ["ru"] = "Установлено (версия неизвестна)" },

        // Models / HuggingFace
        ["models.download_complete"] = new() { ["en"] = "Download complete", ["ru"] = "Загрузка завершена" },
        ["models.hf_token_instructions"] = new() { ["en"] = "Open your browser, create or copy your HuggingFace token, then paste it below.", ["ru"] = "Откройте браузер, создайте или скопируйте токен HuggingFace, затем вставьте его ниже." },
        ["models.token_cleared"] = new() { ["en"] = "Auth token cleared", ["ru"] = "Токен очищен" },
        ["models.token_saved"] = new() { ["en"] = "Auth token saved", ["ru"] = "Токен сохранён" },
        ["models.select_dir"] = new() { ["en"] = "Select Download Directory", ["ru"] = "Выберите папку загрузки" },
        ["models.enter_repo"] = new() { ["en"] = "Enter a HuggingFace URL or repo ID", ["ru"] = "Введите URL или ID репозитория HuggingFace" },
        ["models.fetching_files"] = new() { ["en"] = "Fetching repository files...", ["ru"] = "Получение файлов репозитория..." },
        ["models.already_downloaded"] = new() { ["en"] = "Already downloaded", ["ru"] = "Уже загружено" },
        ["models.no_gguf"] = new() { ["en"] = "No .gguf files found", ["ru"] = "Файлы .gguf не найдены" },
        ["models.no_files_selected"] = new() { ["en"] = "No files selected", ["ru"] = "Файлы не выбраны" },
        ["models.select_dir_first"] = new() { ["en"] = "Select a valid download directory first", ["ru"] = "Сначала выберите папку для загрузки" },
        ["models.downloads_cancelled"] = new() { ["en"] = "Downloads cancelled", ["ru"] = "Загрузки отменены" },
        ["models.invalid_directory"] = new() { ["en"] = "Invalid directory", ["ru"] = "Неверная папка" },
        ["models.scanning"] = new() { ["en"] = "Scanning...", ["ru"] = "Сканирование..." },
        ["models.select_models_dir"] = new() { ["en"] = "Select Models Directory", ["ru"] = "Выберите папку моделей" },
        ["models.enter_repo_first"] = new() { ["en"] = "Enter a model repo first", ["ru"] = "Сначала введите репозиторий модели" },
        ["models.save_token"] = new() { ["en"] = "💾 Save Token", ["ru"] = "💾 Сохранить токен" },
        ["models.hf_download"] = new() { ["en"] = "HuggingFace Download", ["ru"] = "Загрузка из HuggingFace" },

        // API Test
        ["apitest.checking"] = new() { ["en"] = "Checking...", ["ru"] = "Проверка..." },
        ["apitest.status"] = new() { ["en"] = "Status", ["ru"] = "Статус" },
        ["apitest.error"] = new() { ["en"] = "ERROR", ["ru"] = "ОШИБКА" },
        ["apitest.fetching_models"] = new() { ["en"] = "Fetching models...", ["ru"] = "Получение списка моделей..." },
        ["apitest.sending_chat"] = new() { ["en"] = "Sending chat request...", ["ru"] = "Отправка запроса чата..." },
        ["apitest.sending_completion"] = new() { ["en"] = "Sending completion request...", ["ru"] = "Отправка запроса завершения..." },
        ["apitest.empty_path"] = new() { ["en"] = "ERROR: Path is empty", ["ru"] = "ОШИБКА: Путь пуст" },
        ["apitest.sending_custom"] = new() { ["en"] = "Sending custom request...", ["ru"] = "Отправка пользовательского запроса..." },
        ["apitest.unsupported_method"] = new() { ["en"] = "ERROR: Unsupported method: {0}", ["ru"] = "ОШИБКА: Неподдерживаемый метод: {0}" },
        ["apitest.suite_header"] = new() { ["en"] = "=== API Test Suite ===", ["ru"] = "=== Набор тестов API ===" },
        ["apitest.base_url"] = new() { ["en"] = "Base URL", ["ru"] = "Базовый URL" },
        ["apitest.time"] = new() { ["en"] = "Time", ["ru"] = "Время" },
        ["apitest.health_section"] = new() { ["en"] = "--- Health Check ---", ["ru"] = "--- Проверка состояния ---" },
        ["apitest.models_section"] = new() { ["en"] = "--- Models List ---", ["ru"] = "--- Список моделей ---" },

        // Dialog buttons
        ["dialog.ok"] = new() { ["en"] = "OK", ["ru"] = "ОК" },
        ["dialog.cancel"] = new() { ["en"] = "Cancel", ["ru"] = "Отмена" },
        ["dialog.yes"] = new() { ["en"] = "Yes", ["ru"] = "Да" },
        ["dialog.no"] = new() { ["en"] = "No", ["ru"] = "Нет" },
        ["dialog.information"] = new() { ["en"] = "Information", ["ru"] = "Информация" },
        ["dialog.confirmation"] = new() { ["en"] = "Confirmation", ["ru"] = "Подтверждение" },
        ["dialog.error"] = new() { ["en"] = "Error", ["ru"] = "Ошибка" },

        // File picker
        ["picker.save_chat"] = new() { ["en"] = "Save chat session", ["ru"] = "Сохранить сессию чата" },
        ["picker.select_images"] = new() { ["en"] = "Select Images", ["ru"] = "Выбрать изображения" },
        ["picker.select_files"] = new() { ["en"] = "Select Files", ["ru"] = "Выбрать файлы" },

        // Chat page
        ["chat.add_mcp_server"] = new() { ["en"] = "Add MCP Server", ["ru"] = "Добавить MCP-сервер" },
        ["chat.mcp_name"] = new() { ["en"] = "Name:", ["ru"] = "Имя:" },
        ["chat.mcp_type"] = new() { ["en"] = "Type:", ["ru"] = "Тип:" },
        ["chat.mcp_command"] = new() { ["en"] = "Command:", ["ru"] = "Команда:" },
        ["chat.mcp_args"] = new() { ["en"] = "Arguments:", ["ru"] = "Аргументы:" },
        ["chat.mcp_url"] = new() { ["en"] = "URL:", ["ru"] = "URL:" },
        ["chat.mcp_add"] = new() { ["en"] = "Add", ["ru"] = "Добавить" },
        ["chat.tools_count"] = new() { ["en"] = "tools", ["ru"] = "инструментов" },
        ["chat.welcome"] = new() { ["en"] = "Hello!", ["ru"] = "Привет!" },
        ["chat.welcome_sub"] = new() { ["en"] = "Enter a message or load files to get started", ["ru"] = "Введите сообщение или загрузите файлы, чтобы начать работу" },
        ["chat.streaming"] = new() { ["en"] = "(running...)", ["ru"] = "(выполняется...)" },
        ["chat.input_watermark"] = new() { ["en"] = "Type a message...", ["ru"] = "Введите сообщение..." },
        ["chat.cut"] = new() { ["en"] = "Cut", ["ru"] = "Вырезать" },
        ["chat.copy"] = new() { ["en"] = "Copy", ["ru"] = "Копировать" },
        ["chat.paste"] = new() { ["en"] = "Paste", ["ru"] = "Вставить" },
        ["chat.select_all"] = new() { ["en"] = "Select All", ["ru"] = "Выбрать всё" },

        // Monitoring
        ["monitoring.tok_per_sec"] = new() { ["en"] = "tok/s", ["ru"] = "ток/с" },

        // Tray
        ["tray.tooltip"] = new() { ["en"] = "Llama Studio — llama.cpp Manager", ["ru"] = "Llama Studio — менеджер llama.cpp" },
        ["tray.no_profiles"] = new() { ["en"] = "(no profiles)", ["ru"] = "(нет профилей)" },
        ["tray.monitoring"] = new() { ["en"] = "📊 Monitoring", ["ru"] = "📊 Мониторинг" },

        // Executable status
        ["server.exec_found"] = new() { ["en"] = "Executable found: {0}", ["ru"] = "Исполняемый файл найден: {0}" },
        ["server.exec_not_found"] = new() { ["en"] = "Executable not found", ["ru"] = "Исполняемый файл не найден" },

        // Monitoring page
        ["mon.title"] = new() { ["en"] = "Monitoring", ["ru"] = "Мониторинг" },
        ["mon.server_controls"] = new() { ["en"] = "Server Controls", ["ru"] = "Управление сервером" },
        ["mon.model_name"] = new() { ["en"] = "Model", ["ru"] = "Модель" },
        ["mon.start"] = new() { ["en"] = "Start", ["ru"] = "Запустить" },
        ["mon.stop"] = new() { ["en"] = "Stop", ["ru"] = "Остановить" },
        ["mon.restart"] = new() { ["en"] = "Restart", ["ru"] = "Перезапуск" },
        ["mon.tps"] = new() { ["en"] = "Response", ["ru"] = "Ответ" },
        ["mon.prompt_tps"] = new() { ["en"] = "Prompt", ["ru"] = "Промпт" },
        ["mon.gen_label"] = new() { ["en"] = "Response", ["ru"] = "Ответ" },
        ["mon.vram"] = new() { ["en"] = "VRAM", ["ru"] = "VRAM" },
        ["mon.ram"] = new() { ["en"] = "RAM", ["ru"] = "ОЗУ" },
        ["mon.gpu_temp"] = new() { ["en"] = "GPU Temp", ["ru"] = "Темп. GPU" },
        ["mon.power"] = new() { ["en"] = "Power", ["ru"] = "Мощность" },
        ["mon.gpu_core"] = new() { ["en"] = "GPU Core", ["ru"] = "Ядро GPU" },
        ["mon.fan"] = new() { ["en"] = "Fan", ["ru"] = "Вентилятор" },
        ["mon.settings_title"] = new() { ["en"] = "Display Settings", ["ru"] = "Настройки отображения" },
        ["mon.opacity"] = new() { ["en"] = "Opacity", ["ru"] = "Прозрачность" },
        ["mon.always_on_top"] = new() { ["en"] = "Always on Top", ["ru"] = "Всегда сверху" },
        ["mon.visible_metrics"] = new() { ["en"] = "Visible metrics:", ["ru"] = "Видимые метрики:" },
        ["mon.style_title"] = new() { ["en"] = "Display Style", ["ru"] = "Стиль отображения" },
        ["mon.style_bars"] = new() { ["en"] = "Bars", ["ru"] = "Полосы" },
        ["mon.style_circles"] = new() { ["en"] = "Circles", ["ru"] = "Круги" },
        ["mon.style_compact"] = new() { ["en"] = "Compact", ["ru"] = "Компактный" },
        ["mon.open_floating"] = new() { ["en"] = "Open Floating Window", ["ru"] = "Плавающее окно" },
        ["mon.monitoring_on"] = new() { ["en"] = "Monitoring: ON", ["ru"] = "Мониторинг: ВКЛ" },
        ["mon.monitoring_off"] = new() { ["en"] = "Monitoring: OFF", ["ru"] = "Мониторинг: ВЫКЛ" },

        // Dashboard
        ["dash.title"] = new() { ["en"] = "Dashboard", ["ru"] = "Главная" },
        ["dash.server_label"] = new() { ["en"] = "Server", ["ru"] = "Сервер" },
        ["dash.uptime"] = new() { ["en"] = "Uptime: {0}", ["ru"] = "Работает: {0}" },
        ["dash.models_card"] = new() { ["en"] = "Models", ["ru"] = "Модели" },
        ["dash.indexed"] = new() { ["en"] = "Indexed", ["ru"] = "Найдено" },
        ["dash.profiles_card"] = new() { ["en"] = "Profiles", ["ru"] = "Профили" },
        ["dash.saved"] = new() { ["en"] = "Saved", ["ru"] = "Сохранено" },
        ["dash.llama_cpp"] = new() { ["en"] = "llama.cpp", ["ru"] = "llama.cpp" },
        ["dash.active"] = new() { ["en"] = "Active", ["ru"] = "Активна" },
        ["dash.vram_usage"] = new() { ["en"] = "VRAM Usage", ["ru"] = "Использование VRAM" },
        ["dash.gpu_memory"] = new() { ["en"] = "GPU Memory", ["ru"] = "Память GPU" },
        ["dash.active_model"] = new() { ["en"] = "Active Model", ["ru"] = "Активная модель" },
        ["dash.quick_actions"] = new() { ["en"] = "Quick Actions", ["ru"] = "Быстрые действия" },
        ["dash.scan_models"] = new() { ["en"] = "Scan Models", ["ru"] = "Сканировать модели" },
        ["dash.discover_gguf"] = new() { ["en"] = "Discover GGUF files", ["ru"] = "Найти файлы GGUF" },
        ["dash.create_profile"] = new() { ["en"] = "Create Profile", ["ru"] = "Создать профиль" },
        ["dash.launch_config"] = new() { ["en"] = "Launch config", ["ru"] = "Конфиг запуска" },
        ["dash.check_updates"] = new() { ["en"] = "Check Updates", ["ru"] = "Проверить обновления" },
        ["dash.llama_version"] = new() { ["en"] = "llama.cpp version", ["ru"] = "Версия llama.cpp" },
        ["dash.up_to_date"] = new() { ["en"] = "Up to date", ["ru"] = "Версия актуальна" },
        ["dash.update_available"] = new() { ["en"] = "Update available", ["ru"] = "Доступно обновление" },
        ["dash.checking_version"] = new() { ["en"] = "Checking...", ["ru"] = "Проверка..." },
        ["dash.switching_version"] = new() { ["en"] = "Switching to {0}... Restarting server", ["ru"] = "Переключение на {0}... Перезапуск сервера" },
        ["dash.restart_server"] = new() { ["en"] = "Restarting Server", ["ru"] = "Перезапуск сервера" },
["dash.update"] = new() { ["en"] = "Update", ["ru"] = "Обновить" },
         ["dash.updating"] = new() { ["en"] = "Updating", ["ru"] = "Обновление" },
         ["dash.update_installed"] = new() { ["en"] = "Update Installed", ["ru"] = "Обновление установлено" },
         ["dash.update_installed_msg"] = new() { ["en"] = "Version {0} has been installed. Start the server to use it.", ["ru"] = "Версия {0} установлена. Запустите сервер для использования." },
         ["dash.update_restart_server"] = new() { ["en"] = "Version {0} has been installed. Restart the server now?", ["ru"] = "Версия {0} установлена. Перезапустить сервер сейчас?" },
         ["dash.server_restarted"] = new() { ["en"] = "Server restarted with new version", ["ru"] = "Сервер перезапущен с новой версией" },
         ["dash.restart_failed"] = new() { ["en"] = "Failed to restart server", ["ru"] = "Не удалось перезапустить сервер" },
         ["dash.success"] = new() { ["en"] = "Success", ["ru"] = "Успешно" },
         ["dash.error"] = new() { ["en"] = "Error", ["ru"] = "Ошибка" },
         ["dash.app_version"] = new() { ["en"] = "Llama Studio", ["ru"] = "Llama Studio" },
         ["dash.new_version"] = new() { ["en"] = "New version", ["ru"] = "Новая версия" },
         ["dash.downloading"] = new() { ["en"] = "Downloading", ["ru"] = "Загрузка" },
         ["dash.checking_update"] = new() { ["en"] = "Checking...", ["ru"] = "Проверка..." },
        ["dash.gpu_monitor"] = new() { ["en"] = "GPU Monitor", ["ru"] = "Использование GPU" },
        ["dash.live"] = new() { ["en"] = "Live", ["ru"] = "Live" },
        ["dash.vram_label"] = new() { ["en"] = "VRAM Usage", ["ru"] = "VRAM Usage" },
        ["dash.gpu_core"] = new() { ["en"] = "GPU Core", ["ru"] = "GPU Core" },
        ["dash.power_draw"] = new() { ["en"] = "Power Draw", ["ru"] = "Power Draw" },
        ["dash.fan_speed"] = new() { ["en"] = "Fan Speed", ["ru"] = "Fan Speed" },
        ["dash.clock"] = new() { ["en"] = "Clock", ["ru"] = "Clock" },
        ["dash.model"] = new() { ["en"] = "Model", ["ru"] = "Model" },
        ["dash.throughput"] = new() { ["en"] = "Tokens/sec", ["ru"] = "Токенов/сек" },
        ["dash.prompt_throughput"] = new() { ["en"] = "Prompt tok/s", ["ru"] = "Промпт ток/с" },
        ["dash.gpu_temperature"] = new() { ["en"] = "GPU Temperature", ["ru"] = "Температура GPU" },
        ["dash.ram_usage"] = new() { ["en"] = "RAM Usage", ["ru"] = "Загрузка ОЗУ" },
        ["dash.mem_temperature"] = new() { ["en"] = "GPU Memory Temperature", ["ru"] = "Температура памяти GPU" },
        ["dash.profile"] = new() { ["en"] = "Profile", ["ru"] = "Профиль" },
        ["dash.no_profile"] = new() { ["en"] = "No profile", ["ru"] = "Нет профиля" },
        ["dash.main_model"] = new() { ["en"] = "Main Model", ["ru"] = "Основная модель" },
        ["dash.mmproj"] = new() { ["en"] = "Vision (mmproj)", ["ru"] = "Зрение (mmproj)" },
        ["dash.draft_model"] = new() { ["en"] = "Draft Model", ["ru"] = "Черновик" },
        ["dash.context"] = new() { ["en"] = "Context", ["ru"] = "Контекст" },
        ["dash.temperature_label"] = new() { ["en"] = "Temperature", ["ru"] = "Температура" },
        ["dash.gpu_layers"] = new() { ["en"] = "GPU Layers", ["ru"] = "Слои GPU" },
        ["dash.threads"] = new() { ["en"] = "Threads", ["ru"] = "Потоки" },
        ["dash.mtp"] = new() { ["en"] = "MTP", ["ru"] = "MTP" },
        ["dash.reasoning"] = new() { ["en"] = "Reasoning", ["ru"] = "Рассуждение" },
        ["dash.flash_attn"] = new() { ["en"] = "Flash Attention", ["ru"] = "Flash Attention" },
        ["dash.cache_prompt"] = new() { ["en"] = "Cache Prompt", ["ru"] = "Кэш промпта" },
        ["dash.cont_batching"] = new() { ["en"] = "Cont. Batching", ["ru"] = "Непрерывный батч" },
        ["dash.select_profile"] = new() { ["en"] = "Select Profile", ["ru"] = "Выбрать профиль" },
        ["dash.default"] = new() { ["en"] = "default", ["ru"] = "по умолчанию" },
        ["dash.set_default"] = new() { ["en"] = "Set Default", ["ru"] = "Сделать дефолтным" },

        // Models page
        ["models.title"] = new() { ["en"] = "Models", ["ru"] = "Модели" },
        ["models.count"] = new() { ["en"] = "models", ["ru"] = "моделей" },
        ["models.scan"] = new() { ["en"] = "Scan Models", ["ru"] = "Сканировать" },
        ["models.scanning"] = new() { ["en"] = "Scanning...", ["ru"] = "Сканирование..." },
        ["models.browse"] = new() { ["en"] = "Browse...", ["ru"] = "Обзор..." },
        ["models.search"] = new() { ["en"] = "Search models...", ["ru"] = "Поиск моделей..." },
        ["models.no_models"] = new() { ["en"] = "No models found. Set a models directory and click Scan.", ["ru"] = "Модели не найдены. Укажите папку и нажмите Сканировать." },
        ["models.use_default_profile"] = new() { ["en"] = "Use in Default Profile", ["ru"] = "В профиль по умолчанию" },
        ["models.to_server"] = new() { ["en"] = "→ Server Model", ["ru"] = "→ Модель сервера" },
        ["models.to_mmproj"] = new() { ["en"] = "→ Server mmproj", ["ru"] = "→ Сервер mmproj" },
        ["models.to_draft"] = new() { ["en"] = "→ Server Draft", ["ru"] = "→ Черновик сервера" },
        ["models.connected"] = new() { ["en"] = "✓ Connected", ["ru"] = "✓ Подключено" },

        // HuggingFace
        ["hf.title"] = new() { ["en"] = "HuggingFace Download", ["ru"] = "Загрузка с HuggingFace" },
        ["hf.url_placeholder"] = new() { ["en"] = "HuggingFace repo URL or ID (e.g. unsloth/Qwen3.6-27B-MTP-GGUF)", ["ru"] = "URL или ID репозитория HuggingFace (например unsloth/Qwen3.6-27B-MTP-GGUF)" },
        ["hf.auth_token_placeholder"] = new() { ["en"] = "HF auth token (for private repos)", ["ru"] = "Токен авторизации HF (для приватных репозиториев)" },
        ["hf.browse"] = new() { ["en"] = "Browse...", ["ru"] = "Обзор..." },
        ["hf.fetch"] = new() { ["en"] = "Fetch", ["ru"] = "Загрузить список" },
        ["hf.download_selected"] = new() { ["en"] = "Download Selected", ["ru"] = "Скачать выбранные" },
        ["hf.cancel"] = new() { ["en"] = "Cancel", ["ru"] = "Отмена" },
        ["hf.select_all"] = new() { ["en"] = "Select All", ["ru"] = "Выбрать все" },
        ["hf.deselect_all"] = new() { ["en"] = "Deselect All", ["ru"] = "Снять выбор" },
        ["hf.login"] = new() { ["en"] = "Login on HF", ["ru"] = "Войти на HF" },
        ["hf.select_dir"] = new() { ["en"] = "Download to:", ["ru"] = "Скачать в:" },
        ["hf.files_found"] = new() { ["en"] = "files found", ["ru"] = "файлов найдено" },

        // Profiles page
        ["profiles.title"] = new() { ["en"] = "Launch Profiles", ["ru"] = "Профили запуска" },
        ["profiles.new"] = new() { ["en"] = "+ New Profile", ["ru"] = "+ Новый профиль" },
        ["profiles.import"] = new() { ["en"] = "Import JSON", ["ru"] = "Импорт JSON" },
        ["profiles.name_placeholder"] = new() { ["en"] = "Profile name...", ["ru"] = "Имя профиля..." },
        ["profiles.desc_placeholder"] = new() { ["en"] = "Description...", ["ru"] = "Описание..." },
        ["profiles.select_model"] = new() { ["en"] = "Select Model...", ["ru"] = "Выбрать модель..." },
        ["profiles.default_badge"] = new() { ["en"] = "DEFAULT", ["ru"] = "ПО УМОЛЧАНИЮ" },
        ["profiles.set_default"] = new() { ["en"] = "Set Default", ["ru"] = "По умолчанию" },
        ["profiles.edit"] = new() { ["en"] = "Edit", ["ru"] = "Изменить" },
        ["profiles.duplicate"] = new() { ["en"] = "Duplicate", ["ru"] = "Дублировать" },
        ["profiles.export"] = new() { ["en"] = "Export", ["ru"] = "Экспорт" },
        ["profiles.delete"] = new() { ["en"] = "Delete", ["ru"] = "Удалить" },
        ["profiles.save_settings"] = new() { ["en"] = "Save Settings", ["ru"] = "Сохранить настройки" },
        ["profiles.start_server"] = new() { ["en"] = "Start Server", ["ru"] = "Запустить сервер" },

        // Settings page
        ["settings.title"] = new() { ["en"] = "Settings", ["ru"] = "Настройки" },
        ["settings.general_section"] = new() { ["en"] = "General", ["ru"] = "Общие" },
        ["settings.paths_section"] = new() { ["en"] = "Paths", ["ru"] = "Пути" },
        ["settings.llama_cpp_base_dir_label"] = new() { ["en"] = "llama.cpp Base Directory:", ["ru"] = "Корневая папка llama.cpp:" },
        ["settings.llama_cpp_dir_label"] = new() { ["en"] = "llama.cpp:", ["ru"] = "llama.cpp:" },
        ["settings.models_dir_label"] = new() { ["en"] = "Models:", ["ru"] = "Модели:" },
        ["settings.browse_btn"] = new() { ["en"] = "Browse...", ["ru"] = "Обзор..." },
        ["settings.auto_check_updates"] = new() { ["en"] = "Auto-check updates", ["ru"] = "Автопроверка обновлений" },
        ["settings.minimize_to_tray"] = new() { ["en"] = "Minimize to tray on close", ["ru"] = "Сворачивать в трей при закрытии" },
        ["settings.auto_start_with_os"] = new() { ["en"] = "Auto-start with Windows", ["ru"] = "Автозапуск с Windows" },
        ["settings.start_minimized"] = new() { ["en"] = "Start minimized to tray", ["ru"] = "Запускать свёрнутым в трей" },
        ["settings.start_monitoring_window"] = new() { ["en"] = "Start monitoring window", ["ru"] = "Запускать окно мониторинга" },
        ["settings.keep_server_on_exit"] = new() { ["en"] = "Keep server running on exit", ["ru"] = "Не выгружать сервер при закрытии" },
        ["settings.portable_mode"] = new() { ["en"] = "Portable mode", ["ru"] = "Портативный режим" },
        ["settings.theme_label"] = new() { ["en"] = "Theme:", ["ru"] = "Тема:" },
        ["settings.dark"] = new() { ["en"] = "Dark", ["ru"] = "Тёмная" },
        ["settings.light"] = new() { ["en"] = "Light", ["ru"] = "Светлая" },
        ["settings.system"] = new() { ["en"] = "System", ["ru"] = "Системная" },
        ["settings.active_version"] = new() { ["en"] = "Active version:", ["ru"] = "Активная версия:" },
        ["settings.update_channel_label"] = new() { ["en"] = "Update channel:", ["ru"] = "Канал обновлений:" },
        ["settings.stable"] = new() { ["en"] = "Stable", ["ru"] = "Стабильная" },
        ["settings.prerelease"] = new() { ["en"] = "PreRelease", ["ru"] = "Предварительная" },
        ["settings.nightly"] = new() { ["en"] = "Nightly", ["ru"] = "Ночная сборка" },
        ["settings.server_defaults_section"] = new() { ["en"] = "Server Defaults", ["ru"] = "Параметры сервера по умолчанию" },
        ["settings.host_label"] = new() { ["en"] = "Default host:", ["ru"] = "Хост по умолч.:" },
        ["settings.port_label"] = new() { ["en"] = "Default port:", ["ru"] = "Порт по умолч.:" },
        ["settings.gpu_layers_label"] = new() { ["en"] = "Default GPU layers:", ["ru"] = "Слои GPU по умолч.:" },
        ["settings.flash_attention"] = new() { ["en"] = "Enable Flash Attention by default", ["ru"] = "Flash Attention по умолчанию" },
        ["settings.releases"] = new() { ["en"] = "llama.cpp Releases", ["ru"] = "Релизы llama.cpp" },
        ["settings.check_updates_btn"] = new() { ["en"] = "Check for Updates", ["ru"] = "Проверить обновления" },
        ["settings.checking_status"] = new() { ["en"] = "Checking...", ["ru"] = "Проверка..." },
        ["settings.download"] = new() { ["en"] = "Download", ["ru"] = "Скачать" },
        ["settings.save_settings_btn"] = new() { ["en"] = "Save Settings", ["ru"] = "Сохранить настройки" },
        ["settings.published"] = new() { ["en"] = "Published: {0}", ["ru"] = "Дата: {0}" },
        ["settings.language_label"] = new() { ["en"] = "Language:", ["ru"] = "Язык:" },
        ["settings.russian"] = new() { ["en"] = "Русский", ["ru"] = "Русский" },
        ["settings.english"] = new() { ["en"] = "English", ["ru"] = "English" },

        // Logs page
        ["logs.title"] = new() { ["en"] = "Logs", ["ru"] = "Логи" },
        ["logs.entries"] = new() { ["en"] = "entries", ["ru"] = "записей" },
        ["logs.search_placeholder"] = new() { ["en"] = "Filter...", ["ru"] = "Фильтр..." },
        ["logs.min_level_label"] = new() { ["en"] = "Min level:", ["ru"] = "Уровень:" },
        ["logs.export_btn"] = new() { ["en"] = "Export", ["ru"] = "Экспорт" },
        ["logs.clear_btn"] = new() { ["en"] = "Clear", ["ru"] = "Очистить" },
        ["logs.copy_btn"] = new() { ["en"] = "Copy", ["ru"] = "Копировать" },
        ["logs.save_btn"] = new() { ["en"] = "Save", ["ru"] = "Сохранить" },
        ["logs.autoscroll_label"] = new() { ["en"] = "Auto-scroll", ["ru"] = "Автопрокрутка" },
        ["logs.listening_label"] = new() { ["en"] = "Listening", ["ru"] = "Получение" },

        // Chat
        ["chat.title"] = new() { ["en"] = "Chat", ["ru"] = "Чат" },
        ["chat.new_session"] = new() { ["en"] = "New", ["ru"] = "Новый" },
        ["chat.delete_session"] = new() { ["en"] = "Delete", ["ru"] = "Удалить" },
        ["chat.rename_session"] = new() { ["en"] = "Rename", ["ru"] = "Переименовать" },
        ["chat.duplicate_session"] = new() { ["en"] = "Duplicate", ["ru"] = "Дублировать" },
        ["chat.export_session"] = new() { ["en"] = "Export", ["ru"] = "Экспорт" },
        ["chat.clear_session"] = new() { ["en"] = "Clear messages", ["ru"] = "Очистить сообщения" },
        ["chat.delete_session_ctx"] = new() { ["en"] = "Delete", ["ru"] = "Удалить" },
        ["chat.send"] = new() { ["en"] = "Send", ["ru"] = "Отправить" },
        ["chat.stop"] = new() { ["en"] = "Stop", ["ru"] = "Стоп" },
        ["chat.input_watermark"] = new() { ["en"] = "Type a message... (Shift+Enter for new line)", ["ru"] = "Введите сообщение... (Shift+Enter для новой строки)" },
        ["chat.settings"] = new() { ["en"] = "Settings", ["ru"] = "Параметры" },
        ["chat.mcp_tools"] = new() { ["en"] = "MCP Tools", ["ru"] = "MCP-инструменты" },
         ["chat.mcp_servers"] = new() { ["en"] = "MCP Servers", ["ru"] = "MCP" },
         ["chat.mcp_servers_title"] = new() { ["en"] = "MCP Servers", ["ru"] = "MCP-серверы" },
        ["chat.mcp_guide_title"] = new() { ["en"] = "MCP Setup Guide", ["ru"] = "Руководство по настройке MCP" },
        ["chat.mcp_guide_btn"] = new() { ["en"] = "Setup Guide", ["ru"] = "📖 Инструкция" },
        ["chat.select_fs_folder"] = new() { ["en"] = "Select folder for file management", ["ru"] = "Выберите папку для управления файлами" },
        ["chat.fs_description"] = new() { ["en"] = "File system access", ["ru"] = "Доступ к файловой системе" },
        ["chat.fs_configured"] = new() { ["en"] = "Filesystem MCP configured successfully!", ["ru"] = "Filesystem MCP успешно настроен!" },
        ["chat.success"] = new() { ["en"] = "Success", ["ru"] = "Успешно" },
        ["chat.setup_filesystem"] = new() { ["en"] = "Setup Filesystem", ["ru"] = "Настроить Filesystem" },
        ["chat.system_prompt"] = new() { ["en"] = "System Prompt", ["ru"] = "Системный промпт" },
        ["chat.system_prompt_watermark"] = new() { ["en"] = "Enter system instructions...", ["ru"] = "Введите системные инструкции..." },
        ["chat.params"] = new() { ["en"] = "Generation Parameters", ["ru"] = "Параметры генерации" },
        ["chat.sessions"] = new() { ["en"] = "Sessions", ["ru"] = "Сессии" },
        ["chat.no_session"] = new() { ["en"] = "Create a new session to start chatting", ["ru"] = "Создайте новую сессию для начала разговора" },
        ["chat.no_server"] = new() { ["en"] = "Server is not running", ["ru"] = "Сервер не запущен" },
        ["chat.copy"] = new() { ["en"] = "Copy", ["ru"] = "Копировать" },
        ["chat.edit_message"] = new() { ["en"] = "Edit", ["ru"] = "Редактировать" },
        ["chat.regenerate"] = new() { ["en"] = "Regenerate", ["ru"] = "Перегенерировать" },
        ["chat.bookmark"] = new() { ["en"] = "Bookmark", ["ru"] = "Закладка" },
        ["chat.unbookmark"] = new() { ["en"] = "Remove bookmark", ["ru"] = "Убрать закладку" },
        ["chat.delete_message"] = new() { ["en"] = "Delete message", ["ru"] = "Удалить сообщение" },
        ["chat.undo_message"] = new() { ["en"] = "Undo", ["ru"] = "Вернуть" },
["chat.reasoning"] = new() { ["en"] = "Model reasoning", ["ru"] = "Рассуждение модели" },
         ["chat.hide_reasoning"] = new() { ["en"] = "Hide reasoning", ["ru"] = "Скрыть рассуждения" },
         ["chat.server_connected"] = new() { ["en"] = "Connected", ["ru"] = "Подключено" },
         ["chat.server_disconnected"] = new() { ["en"] = "Disconnected", ["ru"] = "Не подключено" },
         ["chat.copy_code"] = new() { ["en"] = "Copy code", ["ru"] = "Копировать код" },
         ["chat.expand_code"] = new() { ["en"] = "Expand code", ["ru"] = "Развернуть код" },

        // Server page — title & buttons
        ["server.title"] = new() { ["en"] = "Server", ["ru"] = "Сервер" },
        ["server.start_btn"] = new() { ["en"] = "Start", ["ru"] = "Запустить" },
        ["server.stop_btn"] = new() { ["en"] = "Stop", ["ru"] = "Остановить" },
        ["server.health_check_btn"] = new() { ["en"] = "Health Check", ["ru"] = "Проверка" },
        ["server.save_profile_btn"] = new() { ["en"] = "Save to Profile", ["ru"] = "Сохранить в профиль" },
    ["server.load_profile_btn"] = new() { ["en"] = "Load Profile", ["ru"] = "Загрузить" },
        ["server.copy_from_profile_btn"] = new() { ["en"] = "Copy", ["ru"] = "Копировать" },
    ["server.create_profile_btn"] = new() { ["en"] = "New Profile", ["ru"] = "Создать" },
    ["server.delete_profile_btn"] = new() { ["en"] = "Delete", ["ru"] = "Удалить" },
    ["server.rename_profile_btn"] = new() { ["en"] = "Rename", ["ru"] = "Переименовать" },
        ["server.delete_profile_btn"] = new() { ["en"] = "Delete", ["ru"] = "Удалить" },
        ["dash.switch_profile_btn"] = new() { ["en"] = "Switch Profile", ["ru"] = "Переключить профиль" },
        ["dash.active_profile_label"] = new() { ["en"] = "Active", ["ru"] = "Активный" },
    ["server.clear_profile_btn"] = new() { ["en"] = "Clear", ["ru"] = "Очистить" },
    ["server.export_profile_btn"] = new() { ["en"] = "Export", ["ru"] = "Экспорт" },
    ["server.import_profile_btn"] = new() { ["en"] = "Import", ["ru"] = "Импорт" },
    ["server.refresh_profiles_btn"] = new() { ["en"] = "Refresh Profiles", ["ru"] = "Обновить профили" },
        ["server.export_bat_btn"] = new() { ["en"] = "Export .bat", ["ru"] = "Экспорт .bat" },
        ["server.copy_cmdline_btn"] = new() { ["en"] = "Copy CmdLine", ["ru"] = "Копировать команду" },
        ["server.no_profile_selected"] = new() { ["en"] = "No profile selected", ["ru"] = "Профиль не выбран" },
        ["server.no_model_selected"] = new() { ["en"] = "No model selected", ["ru"] = "Модель не выбрана" },
        ["server.browse_model_btn"] = new() { ["en"] = "Browse...", ["ru"] = "Обзор..." },
        ["server.browse_mmproj_btn"] = new() { ["en"] = "Browse...", ["ru"] = "Обзор..." },
        ["server.browse_draft_btn"] = new() { ["en"] = "Browse...", ["ru"] = "Обзор..." },
        ["server.quick_scan_btn"] = new() { ["en"] = "Scan Models Dir", ["ru"] = "Сканировать папку" },
        ["server.quick_select_model_btn"] = new() { ["en"] = "Select Model", ["ru"] = "Выбрать модель" },
        ["server.quick_select_mmproj_btn"] = new() { ["en"] = "Select mmproj", ["ru"] = "Выбрать mmproj" },
        ["server.quick_select_draft_btn"] = new() { ["en"] = "Select Draft", ["ru"] = "Выбрать черновик" },
        ["server.check_version_btn"] = new() { ["en"] = "Check Version", ["ru"] = "Проверить версию" },
        ["server.select_llama_dir_btn"] = new() { ["en"] = "Select Directory...", ["ru"] = "Выбрать папку..." },

        // Server page — Model tab
        ["server.state_label"] = new() { ["en"] = "State:", ["ru"] = "Состояние:" },
        ["server.uptime_fmt"] = new() { ["en"] = "Uptime: {0}", ["ru"] = "Работает: {0}" },
        ["server.vram_fmt"] = new() { ["en"] = "VRAM: {0:F1} GB", ["ru"] = "VRAM: {0:F1} ГБ" },
        ["server.ram_fmt"] = new() { ["en"] = "RAM: {0:F1} GB", ["ru"] = "ОЗУ: {0:F1} ГБ" },
        ["server.tps_fmt"] = new() { ["en"] = "TPS: {0:F1}", ["ru"] = "ток/с: {0:F1}" },
        ["server.health_check"] = new() { ["en"] = "Health Check", ["ru"] = "Проверка" },
        ["server.tab_model"] = new() { ["en"] = "Model", ["ru"] = "Модель" },
        ["server.server_path_title"] = new() { ["en"] = "llama.cpp Server Path", ["ru"] = "Путь к llama.cpp серверу" },
        ["server.browse"] = new() { ["en"] = "Browse", ["ru"] = "Обзор" },
        ["server.exec_hint"] = new() { ["en"] = "Server executable will be: llama-server.exe in this folder. Download llama.cpp build and extract here.", ["ru"] = "Исполняемый файл сервера: llama-server.exe в этой папке. Скачайте сборку llama.cpp и распакуйте сюда." },
        ["server.exec_found_fmt"] = new() { ["en"] = "Executable found: {0}", ["ru"] = "Файл найден: {0}" },
        ["server.check_version"] = new() { ["en"] = "Check Version", ["ru"] = "Проверить версию" },
        ["server.main_model"] = new() { ["en"] = "Main Model", ["ru"] = "Основная модель" },
        ["server.model_watermark"] = new() { ["en"] = "Path to .gguf model file", ["ru"] = "Путь к файлу модели .gguf" },
        ["server.mmproj_title"] = new() { ["en"] = "mmproj (Vision)", ["ru"] = "mmproj (Зрение)" },
        ["server.optional"] = new() { ["en"] = "Optional", ["ru"] = "Необязательно" },
        ["server.mmproj_watermark"] = new() { ["en"] = "Path to mmproj .gguf file", ["ru"] = "Путь к файлу mmproj .gguf" },
        ["server.draft_title"] = new() { ["en"] = "Draft Model (Speculative Decoding)", ["ru"] = "Черновая модель (Спекулятивное декодирование)" },
        ["server.advanced_badge"] = new() { ["en"] = "Advanced", ["ru"] = "Продвинуто" },
        ["server.enable_speculative"] = new() { ["en"] = "Enable Speculative Decoding", ["ru"] = "Включить спекулятивное декодирование" },
        ["server.draft_watermark"] = new() { ["en"] = "Path to draft .gguf model", ["ru"] = "Путь к черновой модели .gguf" },
        ["server.quick_select_title"] = new() { ["en"] = "Quick Model Selection (Local)", ["ru"] = "Быстрый выбор модели (локально)" },
        ["server.scan_models_dir"] = new() { ["en"] = "Scan Models Directory", ["ru"] = "Сканировать папку моделей" },
        ["server.to_main"] = new() { ["en"] = "→ Main Model", ["ru"] = "→ Основная модель" },
        ["server.to_mmproj_btn"] = new() { ["en"] = "→ mmproj", ["ru"] = "→ mmproj" },
        ["server.to_draft_btn"] = new() { ["en"] = "→ Draft", ["ru"] = "→ Черновик" },
        ["server.hf_title"] = new() { ["en"] = "HuggingFace — Recommended Models", ["ru"] = "HuggingFace — Рекомендуемые модели" },
        ["server.download_to_fmt"] = new() { ["en"] = "Models will be downloaded to:", ["ru"] = "Модели будут скачаны в:" },
        ["server.select_this_model"] = new() { ["en"] = "Select This Model", ["ru"] = "Выбрать эту модель" },
        ["server.or_manual"] = new() { ["en"] = "Or enter manually:", ["ru"] = "Или ввести вручную:" },
        ["server.repo_label"] = new() { ["en"] = "Repo:", ["ru"] = "Репозиторий:" },
        ["server.offline_mode"] = new() { ["en"] = "Offline mode", ["ru"] = "Офлайн режим" },

        // Server page — GPU tab
        ["server.tab_gpu"] = new() { ["en"] = "GPU", ["ru"] = "GPU" },
        ["server.gpu_acceleration"] = new() { ["en"] = "GPU Acceleration", ["ru"] = "Ускорение GPU" },
        ["server.gpu_layers_label"] = new() { ["en"] = "GPU Layers:", ["ru"] = "Слои GPU:" },
        ["server.threads_label"] = new() { ["en"] = "Threads:", ["ru"] = "Потоки:" },
        ["server.threads_batch_label"] = new() { ["en"] = "Threads Batch:", ["ru"] = "Потоков в батче:" },
        ["server.main_gpu_label"] = new() { ["en"] = "Main GPU:", ["ru"] = "Основной GPU:" },
        ["server.flash_attention"] = new() { ["en"] = "Flash Attention", ["ru"] = "Flash Attention" },
        ["server.memory_map"] = new() { ["en"] = "Memory Map", ["ru"] = "Карта памяти" },
        ["server.mlock"] = new() { ["en"] = "Mlock", ["ru"] = "Mlock" },
        ["server.mmq"] = new() { ["en"] = "MMQ", ["ru"] = "MMQ" },
        ["server.kv_offload"] = new() { ["en"] = "KV Offload", ["ru"] = "Разгрузка KV" },
        ["server.cache_type_k"] = new() { ["en"] = "Cache type K:", ["ru"] = "Тип кэша K:" },
        ["server.cache_type_v"] = new() { ["en"] = "Cache type V:", ["ru"] = "Тип кэша V:" },
        ["server.tip_cache_type_k"] = new() { ["en"] = "KV cache type for K tensors (default: f16)", ["ru"] = "Тип квантования KV-кэша для тензоров K (по умолчанию: f16)" },
        ["server.tip_cache_type_v"] = new() { ["en"] = "KV cache type for V tensors (default: f16)", ["ru"] = "Тип квантования KV-кэша для тензоров V (по умолчанию: f16)" },
 ["server.cache_ram"] = new() { ["en"] = "Cache RAM (MiB):", ["ru"] = "Кэш RAM (МиБ):" },
    ["server.tip_cache_ram"] = new() { ["en"] = "Max KV cache size in MiB (-1 = no limit, 0 = disable, default: 8192)", ["ru"] = "Макс. размер KV-кэша в МиБ (-1 = без лимита, 0 = отключить, по умолчанию: 8192)" },
    ["server.cache_reuse"] = new() { ["en"] = "Cache reuse (tokens):", ["ru"] = "Переиспользование кэша (токены):" },
    ["server.tip_cache_reuse"] = new() { ["en"] = "Min chunk size in tokens to attempt reusing from cache via KV shifting (default: 32, 0=disable)", ["ru"] = "Мин. размер чанка в токенах для переиспользования из кэша через KV-shifting (по умолчанию: 32, 0=отключить)" },

        // Server page — Context & Sampling tab
        ["server.tab_context_sampling"] = new() { ["en"] = "Context & Sampling", ["ru"] = "Контекст и сэмплинг" },
        ["server.context_batch"] = new() { ["en"] = "Context & Batch", ["ru"] = "Контекст и батч" },
        ["server.context_label"] = new() { ["en"] = "Context:", ["ru"] = "Контекст:" },
        ["server.batch_label"] = new() { ["en"] = "Batch:", ["ru"] = "Батч:" },
        ["server.ubatch_label"] = new() { ["en"] = "U-Batch:", ["ru"] = "U-батч:" },
        ["server.max_tokens_label"] = new() { ["en"] = "Max Tokens:", ["ru"] = "Макс токенов:" },
        ["server.sampling_title"] = new() { ["en"] = "Sampling", ["ru"] = "Сэмплинг" },
        ["server.temperature_label"] = new() { ["en"] = "Temperature:", ["ru"] = "Температура:" },
        ["server.top_p_label"] = new() { ["en"] = "Top-P:", ["ru"] = "Top-P:" },
        ["server.top_k_label"] = new() { ["en"] = "Top-K:", ["ru"] = "Top-K:" },
        ["server.min_p_label"] = new() { ["en"] = "Min-P:", ["ru"] = "Min-P:" },
        ["server.typical_p_label"] = new() { ["en"] = "Typical-P:", ["ru"] = "Typical-P:" },
        ["server.repeat_penalty_label"] = new() { ["en"] = "Repeat Penalty:", ["ru"] = "Штраф повторов:" },
        ["server.repeat_last_n_label"] = new() { ["en"] = "Repeat Last N:", ["ru"] = "Повтор. последних N:" },
        ["server.presence_penalty_label"] = new() { ["en"] = "Presence Penalty:", ["ru"] = "Штраф присутствия:" },
        ["server.frequency_penalty_label"] = new() { ["en"] = "Frequency Penalty:", ["ru"] = "Штраф частоты:" },
        ["server.seed_label"] = new() { ["en"] = "Seed:", ["ru"] = "Сид:" },
        ["server.mirostat_sampling"] = new() { ["en"] = "Mirostat Sampling", ["ru"] = "Mirostat сэмплинг" },
        ["server.tau_label"] = new() { ["en"] = "Tau:", ["ru"] = "Тау:" },
        ["server.eta_label"] = new() { ["en"] = "Eta:", ["ru"] = "Эта:" },

        // Server page — Advanced tab
        ["server.tab_advanced"] = new() { ["en"] = "Advanced", ["ru"] = "Продвинутое" },
        ["server.mtp_title"] = new() { ["en"] = "MTP / Multi-Token Prediction", ["ru"] = "MTP / Много-токенное предсказание" },
        ["server.spec_type_label"] = new() { ["en"] = "Spec Type:", ["ru"] = "Тип спекуляции:" },
        ["server.predict_count_label"] = new() { ["en"] = "Max Tokens (-n):", ["ru"] = "Макс. токенов (-n):" },
        ["server.spec_draft_params"] = new() { ["en"] = "Speculative Draft Parameters", ["ru"] = "Параметры спекулятивного черновика" },
        ["server.draft_gpu_layers_label"] = new() { ["en"] = "Draft GPU Layers:", ["ru"] = "Слои GPU черновика:" },
        ["server.draft_n_max_label"] = new() { ["en"] = "Draft N Max:", ["ru"] = "Черновик N макс:" },
        ["server.draft_n_min_label"] = new() { ["en"] = "Draft N Min:", ["ru"] = "Черновик N мин:" },
        ["server.draft_p_split_label"] = new() { ["en"] = "Draft P Split:", ["ru"] = "Черновик P разд.:" },
        ["server.draft_p_min_label"] = new() { ["en"] = "Draft P Min:", ["ru"] = "Черновик P мин:" },
        ["server.yarn_rope_title"] = new() { ["en"] = "YARN / Rope Scaling", ["ru"] = "YARN / Масштабирование Rope" },
        ["server.rope_freq_base_label"] = new() { ["en"] = "Rope Freq Base:", ["ru"] = "Частота Rope база:" },
        ["server.rope_freq_scale_label"] = new() { ["en"] = "Rope Freq Scale:", ["ru"] = "Масштаб частоты Rope:" },
        ["server.yarn_orig_ctx_label"] = new() { ["en"] = "Yarn Orig Ctx:", ["ru"] = "Исх. контекст Yarn:" },
        ["server.advanced_options_title"] = new() { ["en"] = "Advanced Options", ["ru"] = "Дополнительные опции" },
        ["server.numa"] = new() { ["en"] = "NUMA", ["ru"] = "NUMA" },
        ["server.cache_prompt"] = new() { ["en"] = "Cache Prompt", ["ru"] = "Кэш промпта" },
        ["server.cont_batching"] = new() { ["en"] = "Cont. Batching", ["ru"] = "Непрерывный батч" },
        ["server.context_shift"] = new() { ["en"] = "Context Shift", ["ru"] = "Сдвиг контекста" },
        ["server.verbose_logging"] = new() { ["en"] = "Verbose Logging", ["ru"] = "Подробные логи" },
        ["server.web_ui"] = new() { ["en"] = "Web UI", ["ru"] = "Веб-интерфейс" },
        ["server.metrics"] = new() { ["en"] = "Metrics", ["ru"] = "Метрики" },
        ["server.reasoning"] = new() { ["en"] = "Reasoning", ["ru"] = "Рассуждения" },
        ["server.embedding_mode"] = new() { ["en"] = "Embedding Mode", ["ru"] = "Режим эмбеддинга" },
        ["server.priority_high"] = new() { ["en"] = "High Priority", ["ru"] = "Высокий приоритет" },
        ["server.create_profile_btn"] = new() { ["en"] = "Create", ["ru"] = "Создать" },
        ["server.custom_args_title"] = new() { ["en"] = "Custom Arguments", ["ru"] = "Пользовательские аргументы" },
        ["server.custom_args_placeholder"] = new() { ["en"] = "Additional command-line arguments...", ["ru"] = "Дополнительные аргументы командной строки..." },
        ["server.export_title"] = new() { ["en"] = "Export", ["ru"] = "Экспорт" },
        ["server.export_bat"] = new() { ["en"] = "Export as .bat", ["ru"] = "Экспорт в .bat" },
        ["server.copy_cmdline"] = new() { ["en"] = "Copy Command Line", ["ru"] = "Копировать команду" },

        // Server page — Connection tab
        ["server.tab_connection"] = new() { ["en"] = "Connection", ["ru"] = "Подключение" },
        ["server.connection_settings"] = new() { ["en"] = "Connection Settings", ["ru"] = "Настройки подключения" },
        ["server.host_label"] = new() { ["en"] = "Host:", ["ru"] = "Хост:" },
        ["server.port_label"] = new() { ["en"] = "Port:", ["ru"] = "Порт:" },
        ["server.timeout_label"] = new() { ["en"] = "Timeout:", ["ru"] = "Таймаут:" },
        ["server.slots_label"] = new() { ["en"] = "Slots:", ["ru"] = "Слоты:" },
        ["server.profile_label"] = new() { ["en"] = "Profile:", ["ru"] = "Профиль:" },
        ["server.cmdline_preview_title"] = new() { ["en"] = "Command Line", ["ru"] = "Командная строка" },
        ["server.unsupported_flags_title"] = new() { ["en"] = "Unsupported Flags", ["ru"] = "Неподдерживаемые флаги" },
        ["server.unsupported_flags_hint"] = new() { ["en"] = "These flags may not be supported by your llama.cpp build", ["ru"] = "Эти флаги могут не поддерживаться вашей сборкой llama.cpp" },
        ["server.cli_validation_title"] = new() { ["en"] = "CLI Validation", ["ru"] = "Проверка CLI" },
        ["server.validate_cli_btn"] = new() { ["en"] = "Validate Flags", ["ru"] = "Проверить флаги" },
        ["server.validating"] = new() { ["en"] = "Validating...", ["ru"] = "Проверка..." },
        ["server.cli_ok"] = new() { ["en"] = "All flags valid", ["ru"] = "Все флаги корректны" },
        ["server.cli_issues_found"] = new() { ["en"] = "Issues found", ["ru"] = "Обнаружены проблемы" },
        ["server.cli_removed_flags"] = new() { ["en"] = "Removed flags", ["ru"] = "Удалённые флаги" },
        ["server.cli_new_flags"] = new() { ["en"] = "New flags available", ["ru"] = "Доступны новые флаги" },
        ["server.cli_changes_title"] = new() { ["en"] = "CLI Changes Detected", ["ru"] = "Изменения CLI обнаружены" },
        ["server.cli_critical"] = new() { ["en"] = "Critical changes", ["ru"] = "Критические изменения" },
        ["server.download_model_btn"] = new() { ["en"] = "⬇ Download Model", ["ru"] = "⬇ Скачать модель" },
        ["server.downloading_status"] = new() { ["en"] = "Downloading...", ["ru"] = "Скачивание..." },
        ["server.profile_controls"] = new() { ["en"] = "Profile & Controls", ["ru"] = "Профиль и управление" },
        ["server.refresh_profiles"] = new() { ["en"] = "Refresh", ["ru"] = "Обновить" },
        ["server.start_server_btn"] = new() { ["en"] = "▶ Start Server", ["ru"] = "▶ Запустить сервер" },
        ["server.stop_server_btn"] = new() { ["en"] = "⏹ Stop Server", ["ru"] = "⏹ Остановить сервер" },
        ["server.save_to_profile"] = new() { ["en"] = "Save to Profile", ["ru"] = "Сохранить в профиль" },

        // Dialog messages
        ["dialog.profile_exists"] = new() { ["en"] = "A profile with the name \"{0}\" already exists.", ["ru"] = "Профиль с именем «{0}» уже существует." },
        ["dialog.model_not_found"] = new() { ["en"] = "Model file not found:\n{0}", ["ru"] = "Файл модели не найден:\n{0}" },
        ["dialog.profile_created"] = new() { ["en"] = "Profile \"{0}\" created.", ["ru"] = "Профиль «{0}» создан." },
        ["dialog.profile_updated"] = new() { ["en"] = "Profile \"{0}\" updated.", ["ru"] = "Профиль «{0}» обновлён." },
        ["dialog.no_default_profile"] = new() { ["en"] = "No default profile exists. Create a profile first.", ["ru"] = "Нет профиля по умолчанию. Создайте профиль сначала." },
        ["dialog.no_model_selected"] = new() { ["en"] = "Default profile has no model selected.", ["ru"] = "В профиле по умолчанию не выбрана модель." },
        ["dialog.no_profile_to_save"] = new() { ["en"] = "No profile selected to save settings.", ["ru"] = "Не выбран профиль для сохранения настроек." },
        ["dialog.no_profile_to_export"] = new() { ["en"] = "No profile selected to export.", ["ru"] = "Не выбран профиль для экспорта." },
        ["dialog.copy_success"] = new() { ["en"] = "Settings copied from \"{0}\". Change what you need and click \"Save to Profile\".", ["ru"] = "Параметры скопированы из «{0}». Измените что нужно и нажмите «Сохранить в профиль»." },
        ["dialog.server_already_running"] = new() { ["en"] = "Server is already running!", ["ru"] = "Сервер уже запущен!" },
        ["dialog.server_start_failed"] = new() { ["en"] = "Server failed to start.\n\n{0}", ["ru"] = "Не удалось запустить сервер.\n\n{0}" },
        ["dialog.server_start_error"] = new() { ["en"] = "Failed to start server:\n{0}", ["ru"] = "Ошибка запуска сервера:\n{0}" },
        ["dialog.server_stop_error"] = new() { ["en"] = "Failed to stop server:\n{0}", ["ru"] = "Ошибка остановки сервера:\n{0}" },
        ["dialog.server_restart_failed"] = new() { ["en"] = "Server failed to restart.\n\n{0}", ["ru"] = "Не удалось перезапустить сервер.\n\n{0}" },
        ["dialog.server_restart_error"] = new() { ["en"] = "Failed to restart server:\n{0}", ["ru"] = "Ошибка перезапуска сервера:\n{0}" },
        ["server.model_not_selected"] = new() { ["en"] = "No model selected", ["ru"] = "Модель не выбрана" },
        ["server.mmproj_not_selected"] = new() { ["en"] = "No mmproj selected", ["ru"] = "mmproj не выбран" },
        ["server.draft_not_selected"] = new() { ["en"] = "No draft model selected", ["ru"] = "Черновая модель не выбрана" },
        ["server.starting_download"] = new() { ["en"] = "Starting download...", ["ru"] = "Начинаю загрузку..." },
        ["server.download_complete"] = new() { ["en"] = "Downloaded: {0}", ["ru"] = "Скачано: {0}" },
        ["server.download_cancelled"] = new() { ["en"] = "Download cancelled", ["ru"] = "Загрузка отменена" },
        ["server.download_error"] = new() { ["en"] = "Error: {0}", ["ru"] = "Ошибка: {0}" },
        ["server.tip_spec_type"] = new() { ["en"] = "Speculative decoding type: ngram (built-in), draft-mtp (MTP models), draft (external model)", ["ru"] = "Тип спекулятивного декодирования: ngram (встроенный), draft-mtp (MTP-модели), draft (внешняя модель)" },
        ["server.tip_priority_high"] = new() { ["en"] = "Set high process priority for llama-server", ["ru"] = "Установить высокий приоритет процесса llama-server" },
        ["models.hf_status_download_complete"] = new() { ["en"] = "Download complete", ["ru"] = "Загрузка завершена" },
        ["models.hf_status_token_instructions"] = new() { ["en"] = "Open the browser, create/copy your token, then paste it below.", ["ru"] = "Откройте браузер, создайте/скопируйте токен, затем вставьте ниже." },
        ["models.hf_status_token_cleared"] = new() { ["en"] = "Auth token cleared", ["ru"] = "Токен очищен" },
        ["models.hf_status_token_saved"] = new() { ["en"] = "Auth token saved", ["ru"] = "Токен сохранён" },
        ["models.hf_status_enter_repo"] = new() { ["en"] = "Enter a HuggingFace URL or repo ID", ["ru"] = "Введите URL или ID репозитория HuggingFace" },
        ["models.hf_status_fetching"] = new() { ["en"] = "Fetching repository files...", ["ru"] = "Получение файлов репозитория..." },
        ["models.hf_status_already_downloaded"] = new() { ["en"] = "Already downloaded", ["ru"] = "Уже загружено" },
        ["models.hf_status_no_gguf"] = new() { ["en"] = "No .gguf files found", ["ru"] = "Файлы .gguf не найдены" },
        ["models.hf_status_no_files_selected"] = new() { ["en"] = "No files selected", ["ru"] = "Файлы не выбраны" },
        ["models.hf_status_select_dir_first"] = new() { ["en"] = "Select a valid download directory first", ["ru"] = "Сначала выберите папку для загрузки" },
        ["models.hf_status_downloading"] = new() { ["en"] = "Downloading {0} file(s)...", ["ru"] = "Скачивание {0} файл(ов)..." },
        ["models.hf_status_cancelled"] = new() { ["en"] = "Downloads cancelled", ["ru"] = "Загрузки отменены" },
        ["models.hf_status_error"] = new() { ["en"] = "Error: {0}", ["ru"] = "Ошибка: {0}" },
        ["models.scan_status_invalid_dir"] = new() { ["en"] = "Invalid directory", ["ru"] = "Неверная папка" },
        ["models.scan_status_scanning"] = new() { ["en"] = "Scanning...", ["ru"] = "Сканирование..." },
        ["models.scan_status_found"] = new() { ["en"] = "Found {0} models", ["ru"] = "Найдено {0} моделей" },
        ["models.scan_status_set_main"] = new() { ["en"] = "Set as main model: {0}", ["ru"] = "Установлена как основная модель: {0}" },
        ["models.scan_status_set_mmproj"] = new() { ["en"] = "Set as mmproj: {0}", ["ru"] = "Установлен как mmproj: {0}" },
        ["models.scan_status_directory"] = new() { ["en"] = "Directory: {0}", ["ru"] = "Папка: {0}" },
        ["apitest.status_checking"] = new() { ["en"] = "Checking...", ["ru"] = "Проверка..." },
        ["apitest.status_fetching"] = new() { ["en"] = "Fetching models...", ["ru"] = "Загрузка моделей..." },
        ["apitest.status_sending_chat"] = new() { ["en"] = "Sending chat request...", ["ru"] = "Отправка chat-запроса..." },
        ["apitest.status_sending_completion"] = new() { ["en"] = "Sending completion request...", ["ru"] = "Отправка completion-запроса..." },
        ["apitest.status_sending_custom"] = new() { ["en"] = "Sending custom request...", ["ru"] = "Отправка пользовательского запроса..." },
        ["apitest.result_error"] = new() { ["en"] = "ERROR: {0}", ["ru"] = "ОШИБКА: {0}" },

        // Log levels (for ComboBox)
        ["log.debug"] = new() { ["en"] = "Debug", ["ru"] = "Отладка" },
        ["log.information"] = new() { ["en"] = "Information", ["ru"] = "Информация" },
        ["log.warning"] = new() { ["en"] = "Warning", ["ru"] = "Предупреждение" },
        ["log.error"] = new() { ["en"] = "Error", ["ru"] = "Ошибка" },

        // Model metadata (for ModelsPage)
        ["model.ctx_fmt"] = new() { ["en"] = "ctx: {0}", ["ru"] = "контекст: {0}" },
        ["model.vram_fmt"] = new() { ["en"] = "~{0:F1} GB VRAM", ["ru"] = "~{0:F1} ГБ VRAM" },
        ["model.layers_fmt"] = new() { ["en"] = "{0} layers", ["ru"] = "{0} слоёв" },

        // Profile metadata (for ProfilesPage)
        ["profile.ctx_fmt"] = new() { ["en"] = "ctx: {0}", ["ru"] = "контекст: {0}" },
        ["profile.gpu_fmt"] = new() { ["en"] = "gpu: {0}", ["ru"] = "gpu: {0}" },
        ["profile.temp_fmt"] = new() { ["en"] = "temp: {0:F2}", ["ru"] = "температура: {0:F2}" },

        // Dashboard VRAM format
        ["dash.vram_gb_fmt"] = new() { ["en"] = " {0:F1} GB", ["ru"] = " {0:F1} ГБ" },

        // Settings — build type filter
        ["settings.build_type_label"] = new() { ["en"] = "Build type:", ["ru"] = "Тип сборки:" },
        ["settings.cuda12x"] = new() { ["en"] = "CUDA 12.x (Recommended)", ["ru"] = "CUDA 12.x (рекомендуется)" },
        ["settings.cuda13x"] = new() { ["en"] = "CUDA 13.x", ["ru"] = "CUDA 13.x" },
        ["settings.vulkan"] = new() { ["en"] = "Vulkan", ["ru"] = "Vulkan" },
        ["settings.cpu_only"] = new() { ["en"] = "CPU Only", ["ru"] = "Только CPU" },
        ["settings.download_install_btn"] = new() { ["en"] = "Download & Install", ["ru"] = "Скачать и установить" },
        ["settings.install_btn"] = new() { ["en"] = "Install", ["ru"] = "Установить" },
        ["settings.installing_btn"] = new() { ["en"] = "Installing...", ["ru"] = "Установка..." },

        // API Test page
        ["api_test.title"] = new() { ["en"] = "API Test", ["ru"] = "Тест API" },
        ["api_test.health"] = new() { ["en"] = "Health Check", ["ru"] = "Проверка здоровья" },
        ["api_test.models"] = new() { ["en"] = "Models List", ["ru"] = "Список моделей" },
        ["api_test.chat"] = new() { ["en"] = "Chat Completion", ["ru"] = "Chat Completion" },
        ["api_test.completion"] = new() { ["en"] = "Completion", ["ru"] = "Completion" },
        ["api_test.custom"] = new() { ["en"] = "Custom Request", ["ru"] = "Пользовательский запрос" },
        ["api_test.test"] = new() { ["en"] = "Test", ["ru"] = "Тест" },
        ["api_test.run_all"] = new() { ["en"] = "Run All Tests", ["ru"] = "Запустить все тесты" },
        ["api_test.connection_settings"] = new() { ["en"] = "Connection Settings", ["ru"] = "Настройки подключения" },
        ["api_test.host"] = new() { ["en"] = "Host:", ["ru"] = "Хост:" },
        ["api_test.port"] = new() { ["en"] = "Port:", ["ru"] = "Порт:" },
        ["api_test.api_key"] = new() { ["en"] = "API Key:", ["ru"] = "API-ключ:" },
        ["api_test.api_key_optional"] = new() { ["en"] = "Optional", ["ru"] = "Необязательно" },
        ["api_test.timeout"] = new() { ["en"] = "Timeout (s):", ["ru"] = "Таймаут (с):" },
        ["api_test.method"] = new() { ["en"] = "Method:", ["ru"] = "Метод:" },
        ["api_test.path"] = new() { ["en"] = "Path:", ["ru"] = "Путь:" },
        ["api_test.path_watermark"] = new() { ["en"] = "/v1/models or full URL", ["ru"] = "/v1/models или полный URL" },
        ["api_test.body"] = new() { ["en"] = "Body:", ["ru"] = "Тело:" },
        ["api_test.body_watermark"] = new() { ["en"] = "JSON body optional", ["ru"] = "JSON-тело (необязательно)" },
        ["api_test.send"] = new() { ["en"] = "Send", ["ru"] = "Отправить" },
        ["api_test.chat_watermark"] = new() { ["en"] = "Enter a message to send...", ["ru"] = "Введите сообщение..." },
        ["api_test.completion_watermark"] = new() { ["en"] = "Enter text to complete...", ["ru"] = "Введите текст для завершения..." },
        ["api_test.checking"] = new() { ["en"] = "Checking...", ["ru"] = "Проверка..." },
        ["api_test.fetching"] = new() { ["en"] = "Fetching models...", ["ru"] = "Загрузка моделей..." },
        ["api_test.sending_chat"] = new() { ["en"] = "Sending chat request...", ["ru"] = "Отправка chat-запроса..." },
        ["api_test.sending_completion"] = new() { ["en"] = "Sending completion request...", ["ru"] = "Отправка completion-запроса..." },
        ["api_test.sending_custom"] = new() { ["en"] = "Sending custom request...", ["ru"] = "Отправка пользовательского запроса..." },
        ["api_test.error"] = new() { ["en"] = "ERROR: {0}", ["ru"] = "ОШИБКА: {0}" },
        ["api_test.path_empty"] = new() { ["en"] = "ERROR: Path is empty", ["ru"] = "ОШИБКА: Путь пуст" },
        ["api_test.method_unsupported"] = new() { ["en"] = "ERROR: Unsupported method: {0}", ["ru"] = "ОШИБКА: Неподдерживаемый метод: {0}" },
        ["api_test.test_suite"] = new() { ["en"] = "=== API Test Suite ===", ["ru"] = "=== Набор тестов API ===" },
        ["api_test.base_url"] = new() { ["en"] = "Base URL: {0}", ["ru"] = "Базовый URL: {0}" },
        ["api_test.time"] = new() { ["en"] = "Time: {0:HH:mm:ss}", ["ru"] = "Время: {0:HH:mm:ss}" },
        ["api_test.health_section"] = new() { ["en"] = "--- Health Check ---", ["ru"] = "--- Проверка здоровья ---" },
        ["api_test.models_section"] = new() { ["en"] = "--- Models List ---", ["ru"] = "--- Список моделей ---" },
        ["api_test.last_test"] = new() { ["en"] = "Last test: {0:HH:mm:ss}", ["ru"] = "Последний тест: {0:HH:mm:ss}" },

        // ToolTips
        ["tt.language"] = new() { ["en"] = "Select application language (changes apply immediately)", ["ru"] = "Выберите язык приложения (применяется сразу)" },
        ["tt.llama_cpp_base_dir"] = new() { ["en"] = "Root directory where all llama.cpp versions are stored. Leave empty for default (AppData).", ["ru"] = "Корневая папка для всех версий llama.cpp. Оставьте пустым для использования AppData." },
        ["tt.llama_cpp_dir"] = new() { ["en"] = "Directory where llama.cpp binaries are installed. Auto-set after download.", ["ru"] = "Папка с бинарниками llama.cpp. Заполняется автоматически после установки." },
        ["tt.models_dir"] = new() { ["en"] = "Directory where GGUF model files are stored.", ["ru"] = "Папка для хранения файлов моделей GGUF." },
        ["tt.auto_check_updates"] = new() { ["en"] = "Automatically check for new llama.cpp releases on startup", ["ru"] = "Автоматически проверять новые версии llama.cpp при запуске" },
        ["tt.minimize_to_tray"] = new() { ["en"] = "When closing the window, minimize to system tray instead of exiting. Server keeps running.", ["ru"] = "При закрытии окна сворачивать в трей вместо выхода. Сервер продолжает работать." },
        ["tt.auto_start_with_os"] = new() { ["en"] = "Automatically start Llama Studio when Windows logs in. Uses registry run key.", ["ru"] = "Автоматически запускать Llama Studio при входе в Windows. Использует реестр автозагрузки." },
        ["tt.start_minimized"] = new() { ["en"] = "When starting, open the window minimized to system tray instead of showing it.", ["ru"] = "При запуске сворачивать окно в системный трей вместо отображения на экране." },
        ["tt.start_monitoring_window"] = new() { ["en"] = "Show floating monitoring window on startup when running minimized to tray. Disable if you don't want the monitor to appear.", ["ru"] = "Показывать плавающее окно мониторинга при запуске в свёрнутом режиме. Отключите, если не хотите видеть монитор при старте." },
        ["tt.keep_server_on_exit"] = new() { ["en"] = "When closing the application, keep the llama server running in the background. Useful for continuous chat sessions.", ["ru"] = "При закрытии приложения не останавливать llama сервер. Полезно для непрерывных сессий чата." },
        ["tt.portable_mode"] = new() { ["en"] = "Store all data in the application directory instead of AppData", ["ru"] = "Хранить все данные в папке приложения вместо AppData" },
        ["tt.theme"] = new() { ["en"] = "Application appearance theme", ["ru"] = "Тема оформления приложения" },
        ["tt.update_channel"] = new() { ["en"] = "Stable = official releases only. Prerelease includes beta builds.", ["ru"] = "Стабильная = только официальные релизы. Предварительная включает бета-сборки." },
        ["tt.host"] = new() { ["en"] = "Server listen address. 127.0.0.1 = local only, 0.0.0.0 = all interfaces.", ["ru"] = "Адрес сервера. 127.0.0.1 = только локально, 0.0.0.0 = все интерфейсы." },
        ["tt.host_default"] = new() { ["en"] = "Default: 127.0.0.1", ["ru"] = "По умолчанию: 127.0.0.1" },
        ["tt.port"] = new() { ["en"] = "Server port number (1-65535). Default: 8080", ["ru"] = "Порт сервера (1-65535). По умолчанию: 8080" },
        ["tt.port_manual"] = new() { ["en"] = "Enter port number manually", ["ru"] = "Введите номер порта вручную" },
        ["tt.gpu_layers"] = new() { ["en"] = "Number of layers to offload to GPU. 99 = all layers. 0 = CPU only.", ["ru"] = "Количество слоёв для загрузки на GPU. 99 = все слои. 0 = только CPU." },
        ["tt.gpu_layers_default"] = new() { ["en"] = "Default: 99 (all layers on GPU)", ["ru"] = "По умолчанию: 99 (все слои на GPU)" },
        ["tt.flash_attention"] = new() { ["en"] = "Enable Flash Attention for faster inference with lower memory usage", ["ru"] = "Включить Flash Attention для ускорения инференса с меньшим расходом памяти" },
        ["tt.install_build"] = new() { ["en"] = "Download and install this build", ["ru"] = "Скачать и установить эту сборку" },

        // Tray menu
        ["tray.start_server"] = new() { ["en"] = "Start Server", ["ru"] = "Запустить сервер" },
        ["tray.stop_server"] = new() { ["en"] = "Stop Server", ["ru"] = "Остановить сервер" },
        ["tray.restart_server"] = new() { ["en"] = "Restart Server", ["ru"] = "Перезапустить сервер" },
        ["tray.profiles"] = new() { ["en"] = "Profiles", ["ru"] = "Профили" },
        ["tray.show"] = new() { ["en"] = "Show", ["ru"] = "Показать" },
        ["tray.exit"] = new() { ["en"] = "Exit", ["ru"] = "Выход" },
    };

    public string T(string key)
    {
        if (_translations.TryGetValue(key, out var langs) && langs.TryGetValue(_language, out var value))
            return value;
        // Fallback to English
        if (langs != null && langs.TryGetValue("en", out var enValue))
            return enValue;
        return $"[{key}]";
    }

    public void ChangeLanguage(string language)
    {
        _language = language ?? "ru";
        OnLanguageChanged?.Invoke(this, _language);
    }

    public event EventHandler<string>? OnLanguageChanged;
}
